version: "3.10"
services:
  web:
    image: salehtaha/geeksprofile
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    depends_on:
      - "mysql"
  mysql:
    image: mysql:5.7
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=password